# Generated by Django 3.0.4 on 2021-02-05 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_image', models.ImageField(blank=True, upload_to='static/images/')),
                ('item_desc', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diet', models.SmallIntegerField(choices=[(1, 'BreakFast'), (2, 'Lunch'), (3, 'Snacks'), (4, 'Dinner')])),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=600)),
                ('rate', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')])),
                ('foodmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.FoodModel')),
            ],
        ),
    ]
