# Generated by Django 3.0.4 on 2021-02-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='foodmodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FoodApp.FoodModel'),
        ),
    ]
