# Generated by Django 3.0.4 on 2021-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_auto_20210206_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rate',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Dinner', max_length=100),
        ),
    ]
